import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
 
public class MAINFORM extends javax.swing.JFrame {

    /** Creates new form MAINFORM */
    public MAINFORM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1_mod1 = new javax.swing.JButton();
        jButton2_mod2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_Mod1 = new javax.swing.JTextArea();
        jTextField1_K_value = new javax.swing.JTextField();
        jLabel_K_Value = new javax.swing.JLabel();
        jLabel1_N_Value = new javax.swing.JLabel();
        jTextField2_N_Value = new javax.swing.JTextField();
        jTextField1_d = new javax.swing.JTextField();
        jLabel1_d = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_c1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1_mod1.setText("Module 1:Shamir Secret Share Generation");
        jButton1_mod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_mod1MouseClicked(evt);
            }
        });
        jButton1_mod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_mod1ActionPerformed(evt);
            }
        });

        jButton2_mod2.setText("Module 2:Shamir Secrete Recovery");
        jButton2_mod2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_mod2MouseClicked(evt);
            }
        });
        jButton2_mod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_mod2ActionPerformed(evt);
            }
        });

        jTextArea1_Mod1.setColumns(20);
        jTextArea1_Mod1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_Mod1);

        jTextField1_K_value.setEditable(false);
        jTextField1_K_value.setText("2");

        jLabel_K_Value.setText("  k");

        jLabel1_N_Value.setText("  n");

        jTextField2_N_Value.setEditable(false);
        jTextField2_N_Value.setText("6");

        jTextField1_d.setText("0-15");
        jTextField1_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_dActionPerformed(evt);
            }
        });

        jLabel1_d.setText("d secrete ");

        jLabel1.setText("c1 coefficient");

        jTextField1_c1.setText("0-15");

        jLabel2.setText("Enter any two shares");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1_K_value, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel_K_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1_N_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2_N_Value, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_d)
                            .addComponent(jTextField1_d, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jButton1_mod1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButton2_mod2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_mod1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_mod2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_K_value, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2_N_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_K_Value)
                    .addComponent(jLabel1_N_Value)
                    .addComponent(jLabel1_d)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_mod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_mod2ActionPerformed
        // TODO add your handling code here:
         //System.out.println("Enter "+jTextField1_K_value.getText()+"shares");
    }//GEN-LAST:event_jButton2_mod2ActionPerformed

    private void jButton1_mod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_mod1ActionPerformed
        // TODO add your handling code here:
        jTextArea1_Mod1.setText("k= "+jTextField1_K_value.getText()+"  n= "+jTextField2_N_Value.getText()+" Secrete d= "+jTextField1_d.getText());
       //jTextArea1_Mod1.setText("K= "+"\t"+jTextField1_K_value.getText());
        //jTextArea1_Mod1.setText("N= "+"\t"+jTextField2_N_Value.getText());
    }//GEN-LAST:event_jButton1_mod1ActionPerformed

    private void jButton1_mod1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_mod1MouseClicked
        // TODO add your handling code here:
            
            BigInteger d=new BigInteger(jTextField1_d.getText());
            BigInteger c1=new BigInteger(jTextField1_c1.getText());
            
           
             
             
            BigInteger s[] =new BigInteger[2];
         
            s[0]=d;
            s[1]=c1;
            shamirKey[] generateKeys = null;
        try {
            generateKeys = shamir.generateKeys(6,2, 8,s);
        } catch (shamirException ex) {
            Logger.getLogger(MAINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println(d+"  "+c1);
            System.out.println(generateKeys[0].getP());
            for (int i=0;i<6;i++)
            System.out.println(generateKeys[i].getX()+":"+generateKeys[i].getF());
            
            
            
            
            
   jTextArea1_Mod1.setText("k= "+jTextField1_K_value.getText()
           +"  n= "+jTextField2_N_Value.getText()+
           " Secrete d= "+jTextField1_d.getText()+
           "\nF(x)="+"("+jTextField1_d.getText()+
           "+"+jTextField1_c1.getText()+
           "*x)mod17"+"\n\n6 shares :\n "+
           "\nF(1)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*1))%17 +
           "\nF(2)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*2))%17 +
           "\nF(3)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*3))%17 +
           "\nF(4)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*4))%17 +
           "\nF(5)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*5))%17 +
           "\nF(6)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*6))%17 +
           "");
   //jTextArea1_Mod1.setText("N= "+"\t"+jTextField2_N_Value.getText());
    }//GEN-LAST:event_jButton1_mod1MouseClicked

    private void jButton2_mod2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_mod2MouseClicked
        // TODO add your handling code here:
         //jTextArea2_mod2.getSelectedText();
        
       
         System.out.println("Enter "+jTextField1_K_value.getText()+" shares\n");
         BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
         String userName[]=new String[2];
         String split[][] =new String[2][2];
         for(int i=0;i<Integer.parseInt(jTextField1_K_value.getText());i++)
         {System.out.println("Enter "+(i+1)+"th share separated by ;"+"\n");
         try {
             userName[i] = br.readLine();
             String[] sp1= userName[i].split(";");
             split[i][0]=sp1[0];
             split[i][1]=sp1[1];
             System.out.println("x= "+split[i][0]+"\t"+"F(x)="+split[i][1]);
         } catch (IOException ioe) {
             System.out.println("IO error trying to read data!");//System.exit(1);
         } 
         }
                   
     shamirKey[] sk=new shamirKey[2] ;
            //sk[0].setP();
     byte[] val=new byte[1];
     val[0]=17;
     BigInteger bi= new BigInteger(val);
     
    sk[0]=new shamirKey();
    sk[1]=new shamirKey();
    sk[0].setP(bi ); 
    sk[0].setX( new BigInteger(split[0][0]));
    sk[0].setF( new BigInteger(split[0][1]));
    sk[1].setP(BigInteger.valueOf(17)); 
    sk[1].setX( new BigInteger(split[1][0]));
    sk[1].setF( new BigInteger(split[1][1]));
                
         
        
            byte[] calculateLagrange = shamir.calculateLagrange(sk);
            System.out.println(calculateLagrange.length);
            ALGO_2 alg2=new ALGO_2(Integer.parseInt(split[0][0]),Integer.parseInt(split[0][1]),Integer.parseInt(split[1][0]),Integer.parseInt(split[1][1])); 
           // System.out.println("Secrete Recovered: d="+calculateLagrange[0]+"c1="+alg2.get_c1() );
        System.out.println("\n\nSecrete or constant term d of first order polynomial q(x)=(d+c1xi)mod 17 = "+alg2.get_d()+        
           "\n\nCoefficient term c1 of first order polynomial q(x)=(d+c1xi)mod 17 = "+alg2.get_c1());
         
         
            
             /*jTextArea2_mod2.setText( 
           
          
           "\n\n2 shares used :\n "+
           "\nF("+ sk[0].getX()+")="+sk[0].getF()+
           "\nF("+ sk[1].getX()+")="+sk[1].getF()+
           "\n\nSecrete or constant term d of first order \n polynomial q(x)=(d+c1xi)mod 17 = "+alg2.get_d()+        
           "\n\ncoefficient term c1 of first order \n polynomial q(x)=(d+c1xi)mod 17 = "+alg2.get_c1());
         */
    }//GEN-LAST:event_jButton2_mod2MouseClicked

    private void jTextField1_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_dActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new MAINFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_mod1;
    private javax.swing.JButton jButton2_mod2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_N_Value;
    private javax.swing.JLabel jLabel1_d;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_K_Value;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1_Mod1;
    private javax.swing.JTextField jTextField1_K_value;
    private javax.swing.JTextField jTextField1_c1;
    private javax.swing.JTextField jTextField1_d;
    private javax.swing.JTextField jTextField2_N_Value;
    // End of variables declaration//GEN-END:variables

}
